### ISSUE TITLE
NullPointer when view method call MenuItem

### ISSUE THREAD

**Issue by yaroslavyadrov** [Arello-Mobile/Moxy#12]
Hi, Im had issues when view method has AddToEndSingle strategy and implementation of this method call MenuItems. Basically in the moment after screen rotate menu items still null when ViewState try to reapply commands to view. What can I do in that situation?

**Comment by senneco** [comment]
Hi, @yaroslavyadrov. Currently, library doesn't have solution for this. I can suggest to you one solution. You can call method `getMvpDelegate().onAttach()` in `onCreateOptionsMenu(Menu)` method. Then commands will be applyed only when menu will be inflated. But then you shouldn't call `getMvpDelegate().onAttach()` in `onStart()` method. Then you can't use some `BaseMvpActivity`. But this looks right solution. Then all commands will be called in right order.

It's seems like a good place to change of `BaseMvpActivity`.

PS: it will not works on android less than v3.0.

**Comment by yaroslavyadrov** [comment]
Thank you, @senneco. I thought about this solution, but I decide to call Presenter method like `setSavedMenuItemState()` in `OnCreateOptionsMenu` and restore saved MenuItems state. Looks like dirty hack, but works.

**Comment by senneco** [comment]
Glad you found the solution =)

I would recommend a similar solution, but I wasn't sure that it will help you. For example, after you select menu item, a map will be added on the screen. And second command is "add pins to map". In this case, if view is in restore state, the "add pins" will not work because screen has not the map, yet.
