### ISSUE TITLE
Disable view states

### ISSUE THREAD

**Issue by UvarovBoris** [Arello-Mobile/Moxy#161]
Hi, is it possible disable view states restoring feature? For example, I want MVP from Moxy, but I dont want view states and just want save state in onSaveInstance and restore in onRestoreInstance.

**Comment by senneco** [comment]
Hi. Yes, it's possible =) Just don't apply `@InjectViewState` for your presenter. But then you don't be able to use `getViewState()` method (because it will return `null`). You should use `getAttachedViews()` then.

Also, you can apply `@StateStrategyType(SkipStrategy.class)` to your View's interface. Then Moxy won't restore state of your view =)

**Comment by UvarovBoris** [comment]
All clear, thanks.
