### ISSUE TITLE
Redundant prefix "Mvp"

### ISSUE THREAD

**Issue by Yukooo** [Arello-Mobile/Moxy#93]
First of all, you've done a great work with no doubts and now it is even more than the MVP approach so why don't remove the prefix "Mvp" from everywhere.

**Comment by senneco** [comment]
Well, it may be not sense if we name MVP-View as `View` instead of `MvpView` (because Android already contains `View`). As well it may be not sense if we name MVP-Presenter as `Presenter` whereas MVP-View named as `MvpView`.

Whatever, you can make you own simple `Presenter` that extends `MvpPresenter`. Then you can extends from clear `Presenter` =)
